---
driver:
  name: vagrant
  provider: libvirt
  customize:
    cpus: 2

transport:
  name: sftp

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
  - name: centos-7.3
    driver:
      box: "centos/7"
  - name: rhel
    driver:
      box: "generic/rhel7"

suites:
  - name: concourse
    data_bags_path: "fixtures/data_bags" 
    driver:
      network:
        - ["forwarded_port", {guest: 8080, host: 8080}]
    attributes:
      concourse:
        web:
          CONCOURSE_LOG_LEVEL: debug
    run_list:
      - recipe[knc_concourse::default]
